### PR TITLE
feat: center filter component and some padding

### PR DESCRIPTION
**Pull request by angristan**
What do you think? 🤔 

| Before   |      After      | 
|----------|:-------------:|
| screenshot_2021-08-05_02-09-32 | screenshot_2021-08-05_02-09-44 |

### CODE REVIEW

**Review by katsukixyz — CHANGES_REQUESTED** [review]
Center and padding look good, but its current implementation nullifies the sticky CSS

**Comment by angristan** [comment]
> Center and padding look good, but its current implementation nullifies the sticky CSS

My bad! I didn't notice it was sticky 😅

**Comment by angristan** [comment]
It should be better now, let me know what you think 👍

**Comment by katsukixyz** [comment]
Looks good! Appreciate the contribution!

**Review by katsukixyz — APPROVED** [review]

**Pull request merged**
